apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "cols-api.name" . }}
  chart: {{ template "cols-api.chart" . }}
  release: {{ .Release.Name }}
  releaseNumber: {{ $.Values.releaseNumber }}
  heritage: {{ .Release.Service }}
spec:
  host: {{ template "cols-api.name" . }}
  subsets:
  {{- range $i, $slot := .Values.canary }}
  - name: {{ $slot.name }}
    labels:
      tag: '{{ $slot.tag }}'
  {{- end}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "cols-api.name" . }}
  chart: {{ template "cols-api.chart" . }}
  release: {{ .Release.Name }}
  releaseNumber: {{ $.Values.releaseNumber }}
  heritage: {{ .Release.Service }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ template "cols-api.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    {{- range $i, $slot := .Values.canary }}
    - destination:
        host: {{ template "cols-api.fullname" $ }}
        subset: {{ $slot.name }}
      weight: {{ $slot.weight }}
    {{- end}}