apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "cols-api.fullname" . }}-gateway
  chart: {{ template "cols-api.chart" . }}
  release: {{ .Release.Name }}
  releaseNumber: {{ .Values.releaseNumber }}
  heritage: {{ .Release.Service }}
spec:
  selector:
    istio: {{ .Values.gateway.selector }}
  servers:
  - port:
      number: {{ .Values.gateway.port }}
      name: http
      protocol: HTTP
    hosts:
    - "*"