apiVersion: v1
kind: Service
metadata:
  name: cols-api
  labels:
    app: cols-api
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: cols-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cols-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cols-api
    spec:
      containers:
      - name: cols-api
        image: col/api:1.0.0
        imagePullPolicy: IfNotPresent
---