# Default values for cols-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: col/api
  pullPolicy: IfNotPresent

canary:
  - name: blue
    weight: 100
    tag: 1.0.0
  - name: green
    weight: 0
    tag: 1.0.1

service:
  type: NodePort
  port: 80

gateway:
  port: 80
  selector: ingressgateway

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
