apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cols-api-1.0.0
  labels:
    app: cols-api
    version: '1.0.0'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cols-api
        version: '1.0.0'
    spec:
      containers:
      - name: cols-api
        image: col/api:1.0.0
        imagePullPolicy: IfNotPresent